include: package:flutter_lints/rules.yaml

linter:
  rules:
    - unawaited_futures
    - use_build_context_synchronously
    - always_declare_return_types
    - avoid_print
    - prefer_const_constructors
    - prefer_final_fields
    - sized_box_for_whitespace
    - use_key_in_widget_constructors

analyzer:
  exclude:
    - "build/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    todo: ignore
    missing_required_param: error
    missing_return: error
    invalid_assignment: error
